root: true
parser: "@typescript-eslint/parser"

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - next/core-web-vitals
  - plugin:prettier/recommended

plugins:
  - "@typescript-eslint"
