name: CI

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: validate branch name
        run: bash scripts/check_branch.sh ${{ github.head_ref }}

      - name: setup
        uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: "yarn"

      - name: install
        run: yarn

      - name: lint
        run: yarn lint
